jq -s 'reduce .[] as $item ({}; . * $item) | .info.title = "KubeRay API" | .info.description = "This file contains REST API specification for Kuberay. The file is autogenerated from the swagger definition." | .info.version = "v0.1.0" | .info.contact = { "name": "ray-community", "url": "https://ray.io" } | .info.license = { "name": "Apache 2.0", "url": "https://raw.githubusercontent.com/ray-project/kuberay/master/LICENSE" }' \
    cluster.swagger.json \
    error.swagger.json \
    runtime.swagger.json \
    > "kuberay_api_single_file.swagger.json"
