// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ray-project/ray-contrib/ray-operator/api/raycluster/v1alpha1"
	"github.com/ray-project/ray-contrib/ray-operator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type RayclusterV1alpha1Interface interface {
	RESTClient() rest.Interface
	RayClustersGetter
}

// RayclusterV1alpha1Client is used to interact with features provided by the raycluster.ray.io group.
type RayclusterV1alpha1Client struct {
	restClient rest.Interface
}

func (c *RayclusterV1alpha1Client) RayClusters(namespace string) RayClusterInterface {
	return newRayClusters(c, namespace)
}

// NewForConfig creates a new RayclusterV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*RayclusterV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &RayclusterV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new RayclusterV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *RayclusterV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new RayclusterV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *RayclusterV1alpha1Client {
	return &RayclusterV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *RayclusterV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
