// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ray-project/ray-contrib/ray-operator/pkg/client/clientset/versioned/typed/raycluster/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeRayclusterV1alpha1 struct {
	*testing.Fake
}

func (c *FakeRayclusterV1alpha1) RayClusters(namespace string) v1alpha1.RayClusterInterface {
	return &FakeRayClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRayclusterV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
